# Generated by Django 6.0.1 on 2026-02-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='owener_id',
            new_name='owner_id',
        ),
    ]
